#!/bin/zsh
alias vim=nvim
alias note="vim $HOME/note.md"
# Disable zsh correction for following commands
alias git="nocorrect git"
alias log="nocorrect log"
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias g='grep -rnw . -e $*'
alias light='unset DARK; $HOME/scripts/light.sh'
alias dark='$HOME/scripts/dark.sh'
alias speakers='$HOME/scripts/speakers.sh'
alias headset='$HOME/scripts/headset.sh'
alias tmux="tmux -2"
